management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
server:
 port: 9091
spring:
 profiles:
    active:
    - dev     